### ISSUE TITLE
[Feature Request] Font drop-down

### ISSUE THREAD

**Issue by brknsoul** [NaitLee/kitty-printer#4]
Currently, the font selection is a typeable box. It should be a drop-down with available fonts, instead of guessing.

**Comment by NaitLee** [comment]
Thanks for the feature hint. It’s something easy nowadays.

Now in them menu there’s a “Click to load fonts” button, by clicking that & giving permission to Chrome, you have all fonts on your machine to select in a drop-down list.

In case the browser can't load font list (such as on mobile browsers) it’s still a typeable box.

**Comment by brknsoul** [comment]
Excellent. Works well, thank you!
